export function normalizeSearchText(value){return String(value??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}

function lyricLines(song){return(song.slides||[]).flatMap((slide,slideIndex)=>String(slide.text??'').split('\n').map(text=>({text:text.trim(),slide,slideIndex}))).filter(item=>item.text)}

export function createSongSearchIndex(songs=[]){return songs.map(song=>{const lines=lyricLines(song);return{song,normalizedTitle:normalizeSearchText(song.title),normalizedAuthor:normalizeSearchText(song.author),normalizedLyrics:normalizeSearchText(lines.map(item=>item.text).join(' ')),lines}})}

export function highlightRange(original,query){const target=normalizeSearchText(query);if(!target)return null;let normalized='',lastWasSpace=true;const positions=[];for(let index=0;index<String(original).length;index++){const char=String(original)[index].normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase();for(const part of char){if(/[a-z0-9]/.test(part)){normalized+=part;positions.push(index);lastWasSpace=false}else if(!lastWasSpace&&normalized){normalized+=' ';positions.push(index);lastWasSpace=true}}}normalized=normalized.trimEnd();const start=normalized.indexOf(target);if(start<0)return null;return{start:positions[start],end:(positions[start+target.length-1]??positions[start])+1}}

export function searchSongs(index,query){const needle=normalizeSearchText(query);if(!needle)return index.map(entry=>entry.song);return index.map(entry=>{const titleExact=entry.normalizedTitle===needle,titleStarts=!titleExact&&entry.normalizedTitle.startsWith(needle),titleContains=!titleExact&&!titleStarts&&entry.normalizedTitle.includes(needle),lyricContains=entry.normalizedLyrics.includes(needle),authorContains=entry.normalizedAuthor.includes(needle);if(!titleExact&&!titleStarts&&!titleContains&&!lyricContains&&!authorContains)return null;const lineMatch=entry.lines.find(item=>normalizeSearchText(item.text).includes(needle));const slideMatch=lineMatch||entry.lines.find(item=>normalizeSearchText(item.slide.text).includes(needle));let score=titleExact?600:titleStarts?500:titleContains?400:lyricContains?300:100;if(lyricContains)score+=Math.min(50,needle.length);return{...entry.song,searchScore:score,matchKind:titleExact||titleStarts||titleContains?'title':lyricContains?'lyric':'author',matchText:lyricContains?(lineMatch?.text||slideMatch?.slide.text||''):authorContains?entry.song.author:'',matchSlide:lyricContains?slideMatch?.slide:null,highlight:lyricContains?highlightRange(lineMatch?.text||slideMatch?.slide.text||'',query):null}}).filter(Boolean).sort((a,b)=>b.searchScore-a.searchScore||a.title.localeCompare(b.title))}
