import { app, BrowserWindow, dialog, ipcMain, nativeImage, screen } from 'electron';
import { basename, dirname, extname, join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { once } from 'node:events';
import { appendFileSync, copyFileSync, existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { createPresenterServer } from '../server/app.js';
import { openPresenterLibrary } from '../server/presenter-library.js';
const root=dirname(dirname(fileURLToPath(import.meta.url)));
const smoke=process.argv.includes('--smoke-test');
app.setName('SLC Presenter');
if(smoke&&process.env.SLC_PRESENTER_SMOKE_DIR)app.setPath('userData',process.env.SLC_PRESENTER_SMOKE_DIR);
let server,library,origin,mainWindow,audienceWindow,audienceDisplayId,sessionPath,logPath,lastOutputState={},wasUnclean=false,quitting=false,closePending=false,closeApproved=false;
function log(scope,message,details=''){try{appendFileSync(logPath,`${new Date().toISOString()} [${scope}] ${message}${details?` | ${details}`:''}\n`)}catch{}}
function isLocal(url){try{return new URL(url).origin===origin}catch{return false}}
function openWindow(path='/presenter'){const win=new BrowserWindow({width:1440,height:900,minWidth:1100,minHeight:700,show:!smoke,backgroundColor:'#090e17',icon:join(root,'build','icon.png'),webPreferences:{preload:join(root,'desktop','preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});win.webContents.setWindowOpenHandler(({url})=>{if(isLocal(url))openWindow(new URL(url).pathname);return{action:'deny'}});win.loadURL(origin+path);return win}
function displays(){const primary=screen.getPrimaryDisplay();return screen.getAllDisplays().map((display,index)=>({id:String(display.id),label:display.id===primary.id?`Display ${index+1} (Primary)`:`Display ${index+1}`,primary:display.id===primary.id,bounds:display.bounds,size:display.size,scaleFactor:display.scaleFactor}))}
const imageExtensions=new Set(['.jpg','.jpeg','.png','.webp','.bmp','.gif']),videoExtensions=new Set(['.mp4','.webm','.mov','.m4v']);
function mediaTitle(path){return basename(path,extname(path)).replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim().replace(/\b\w/g,letter=>letter.toUpperCase())}
function openAudience(displayId){const available=screen.getAllDisplays(),target=available.find(display=>String(display.id)===String(displayId))||available.find(display=>display.id!==screen.getPrimaryDisplay().id)||available[0];if(!target)throw new Error('No display is available.');audienceWindow?.destroy();audienceDisplayId=String(target.id);audienceWindow=new BrowserWindow({x:target.bounds.x,y:target.bounds.y,width:target.bounds.width,height:target.bounds.height,frame:false,fullscreen:true,kiosk:true,show:true,skipTaskbar:true,autoHideMenuBar:true,backgroundColor:'#000',webPreferences:{preload:join(root,'desktop','preload.cjs'),nodeIntegration:false,contextIsolation:true,sandbox:true}});audienceWindow.setMenuBarVisibility(false);audienceWindow.webContents.once('did-finish-load',()=>audienceWindow?.webContents.send('presenter:output-state',lastOutputState));audienceWindow.loadURL(origin+'/presenter-output');audienceWindow.on('closed',()=>{audienceWindow=null;audienceDisplayId=null;mainWindow?.webContents.send('presenter:output-status',{active:false})});return{active:true,displayId:audienceDisplayId,label:displays().find(display=>display.id===audienceDisplayId)?.label}}
app.whenReady().then(async()=>{
  const dataDir=join(app.getPath('userData'),'data'),mediaDir=join(app.getPath('userData'),'media');mkdirSync(dataDir,{recursive:true});mkdirSync(mediaDir,{recursive:true});logPath=join(dataDir,'presenter.log');log('startup','SLC Presenter starting');
  sessionPath=join(dataDir,'session-state.json');try{wasUnclean=existsSync(sessionPath)&&JSON.parse(readFileSync(sessionPath,'utf8')).clean===false}catch{wasUnclean=true}if(!smoke)writeFileSync(sessionPath,JSON.stringify({clean:false,startedAt:Date.now()}));
  library=openPresenterLibrary(join(dataDir,'presenter.sqlite'));
  server=createPresenterServer(join(root,'dist'),{mediaFile:id=>library.getMediaPath(id)});server.listen(0,'127.0.0.1');await once(server,'listening');origin=`http://127.0.0.1:${server.address().port}`;
  ipcMain.handle('presenter:list-songs',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid library request.');return library.listSongs()});
  ipcMain.handle('presenter:save-song',(event,song)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid library request.');return library.saveSong(song)});
  ipcMain.handle('presenter:delete-song',(event,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid library request.');return library.deleteSong(id)});
  ipcMain.handle('presenter:list-documents',(event,kind)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid library request.');return library.listDocuments(kind)});
  ipcMain.handle('presenter:save-document',(event,item)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid library request.');return library.saveDocument(item)});
  ipcMain.handle('presenter:delete-document',(event,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid library request.');return library.deleteDocument(id)});
  ipcMain.handle('presenter:list-services',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid service request.');return library.listServices()});
  ipcMain.handle('presenter:get-service',(event,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid service request.');return library.getService(id)});
  ipcMain.handle('presenter:save-service',(event,service)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid service request.');return library.saveService(service)});
  ipcMain.handle('presenter:save-service-file',async(event,service,filePath,saveAs=false)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid service file request.');const servicesDir=join(app.getPath('documents'),'SLC Presenter','Services');mkdirSync(servicesDir,{recursive:true});let target=!saveAs&&filePath?filePath:null;if(!target){const result=await dialog.showSaveDialog(BrowserWindow.fromWebContents(event.sender),{title:'Save SLC Presenter Service',defaultPath:join(servicesDir,`${String(service?.name||'New Service').replace(/[<>:"/\\|?*]/g,'-')}.slcservice`),filters:[{name:'SLC Presenter Service',extensions:['slcservice']}]});if(result.canceled)return null;target=result.filePath}if(extname(target).toLowerCase()!=='.slcservice')target+= '.slcservice';const payload={format:'SLC Presenter Service',version:1,name:String(service?.name||'New Service'),savedAt:new Date().toISOString(),items:Array.isArray(service?.items)?service.items:[]};writeFileSync(target,JSON.stringify(payload,null,2),'utf8');log('service','Service file saved',target);return{filePath:target,name:payload.name,savedAt:payload.savedAt}});
  ipcMain.handle('presenter:open-service-file',async(event,directPath)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid service file request.');let target=directPath;if(!target){const servicesDir=join(app.getPath('documents'),'SLC Presenter','Services');mkdirSync(servicesDir,{recursive:true});const result=await dialog.showOpenDialog(BrowserWindow.fromWebContents(event.sender),{title:'Open SLC Presenter Service',defaultPath:servicesDir,properties:['openFile'],filters:[{name:'SLC Presenter Service',extensions:['slcservice']}]});if(result.canceled)return null;target=result.filePaths[0]}const parsed=JSON.parse(readFileSync(target,'utf8'));if(parsed?.format!=='SLC Presenter Service'||Number(parsed.version)!==1||!Array.isArray(parsed.items))throw new Error('This is not a supported SLC Presenter service file.');return{filePath:target,name:String(parsed.name||basename(target,'.slcservice')),items:parsed.items,savedAt:parsed.savedAt||null}});
  ipcMain.handle('presenter:list-bible-translations',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid Bible request.');return library.listTranslations()});
  ipcMain.handle('presenter:list-bible-books',(event,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid Bible request.');return library.listBibleBooks(id)});
  ipcMain.handle('presenter:list-bible-verses',(event,id,book,chapter)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid Bible request.');return library.listBibleVerses(id,book,chapter)});
  ipcMain.handle('presenter:import-bible',async event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid Bible request.');const result=await dialog.showOpenDialog(BrowserWindow.fromWebContents(event.sender),{title:'Import Bible translations',properties:['openFile','multiSelections'],filters:[{name:'Bible JSON',extensions:['json']}]});if(result.canceled)return null;const imported=[],failed=[];for(const path of result.filePaths){try{const translation=library.importBible(path);imported.push(translation);log('bible','Bible translation imported',`${translation.code}: ${translation.verseCount} verses`)}catch(error){failed.push({file:basename(path),error:error.message});log('bible','Bible import failed',`${path} | ${error.stack||error.message}`)}}return{ok:imported.length>0,imported,failed,error:imported.length?'Some selected Bible files could not be imported.':'Unable to import the selected Bible translations. Use supported JSON Bible files. No existing translations were changed.'}});
  ipcMain.handle('presenter:list-media',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid media request.');return library.listMedia()});
  const importMediaPaths=paths=>{const imported=[],failed=[];for(const source of paths){const extension=extname(source).toLowerCase(),isVideo=videoExtensions.has(extension),isImage=imageExtensions.has(extension);if(!isVideo&&!isImage){failed.push({file:basename(source),error:'Unsupported media format'});continue}const id=randomUUID(),stored=join(mediaDir,`${id}${extension}`);try{copyFileSync(source,stored);const size=isImage?nativeImage.createFromPath(stored).getSize():{width:0,height:0};if(isImage&&(!size.width||!size.height))throw new Error('The image could not be decoded.');imported.push(library.addMedia({id,title:mediaTitle(source),type:isVideo?'Video':'Image',path:stored,originalPath:source,mime:isVideo?`video/${extension.slice(1)}`:`image/${extension.slice(1)}`,width:size.width,height:size.height}))}catch(error){try{unlinkSync(stored)}catch{}failed.push({file:basename(source),error:error.message});log('media','Media import failed',`${source} | ${error.stack||error.message}`)}}log('media','Media import completed',`${imported.length}/${paths.length} files`);return{imported,failed}};
  ipcMain.handle('presenter:import-media',async event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid media request.');const result=await dialog.showOpenDialog(BrowserWindow.fromWebContents(event.sender),{title:'Import images or videos',properties:['openFile','multiSelections'],filters:[{name:'Images and videos',extensions:['png','jpg','jpeg','webp','bmp','gif','mp4','webm','mov','m4v']}]});if(result.canceled)return null;return importMediaPaths(result.filePaths)});
  ipcMain.handle('presenter:import-media-paths',(event,paths)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid media request.');return importMediaPaths(Array.isArray(paths)?paths:[])});
  ipcMain.handle('presenter:update-media',(event,id,input)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid media request.');return library.updateMedia(id,input||{})});
  ipcMain.handle('presenter:delete-media',(event,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid media request.');const path=library.getMediaPath(id),deleted=library.deleteMedia(id);if(deleted&&path)try{unlinkSync(path)}catch{}return deleted});
  ipcMain.handle('presenter:list-themes',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid theme request.');return library.listThemes()});
  ipcMain.handle('presenter:save-theme',(event,theme)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid theme request.');return library.saveTheme(theme)});
  ipcMain.handle('presenter:delete-theme',(event,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid theme request.');return library.deleteTheme(id)});
  ipcMain.handle('presenter:theme-defaults',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid theme request.');return library.getThemeDefaults()});
  ipcMain.handle('presenter:set-theme-default',(event,kind,id)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid theme request.');return library.setThemeDefault(kind,id)});
  ipcMain.handle('presenter:session-state',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid session request.');return{wasUnclean}});
  ipcMain.handle('presenter:list-displays',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid display request.');return displays()});
  ipcMain.handle('presenter:open-output',(event,displayId)=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid display request.');return openAudience(displayId)});
  ipcMain.handle('presenter:close-output',event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid display request.');audienceWindow?.close();return{active:false}});
  ipcMain.on('presenter:output-state',(event,state)=>{if(!isLocal(event.senderFrame.url)||!state||typeof state!=='object')return;lastOutputState=state;audienceWindow?.webContents.send('presenter:output-state',state)});
  ipcMain.on('presenter:close-response',(event,approved)=>{if(!isLocal(event.senderFrame.url))return;closePending=false;if(!approved)return;closeApproved=true;app.quit()});
  ipcMain.handle('presenter:import-library',async event=>{if(!isLocal(event.senderFrame.url))throw new Error('Invalid import request.');const result=await dialog.showOpenDialog(BrowserWindow.fromWebContents(event.sender),{title:'Import presentation library',properties:['openFile'],filters:[{name:'Presentation libraries',extensions:['db','sqlite','sqlite3','json']}]});if(result.canceled)return null;try{const imported=library.importFile(result.filePaths[0]);log('import','Library import completed',`${imported.source}: ${imported.imported} added, ${imported.skipped} skipped`);return{ok:true,...imported}}catch(error){log('import','Library import failed',`${result.filePaths[0]} | ${error.stack||error.message}`);return{ok:false,error:'Unable to import library. The selected file is unsupported, corrupted, or not a valid presentation database. No changes were made to your current library.'}}});
  mainWindow=openWindow();
  mainWindow.on('close',event=>{if(quitting||closeApproved)return;event.preventDefault();if(closePending)return;closePending=true;log('shutdown','Operator window requested application close');mainWindow?.webContents.send('presenter:close-request')});
  mainWindow.on('closed',()=>{mainWindow=null});
  screen.on('display-removed',(_,display)=>{if(String(display.id)!==audienceDisplayId)return;audienceWindow?.destroy();audienceWindow=null;audienceDisplayId=null;mainWindow?.webContents.send('presenter:output-status',{active:false,warning:'Audience display disconnected. Live state has been preserved.'})});
  if(smoke){await once(mainWindow.webContents,'did-finish-load');const ready=await mainWindow.webContents.executeJavaScript("Boolean(document.querySelector('.presenter-app'))");if(!ready)throw new Error('Presenter did not render');mainWindow.close()}
}).catch(error=>{log('startup','Startup failed',error.stack||error.message);dialog.showErrorBox('SLC Presenter could not start','The application database or startup files could not be opened. Your data was not modified. See presenter.log for technical details.');app.exit(1)});
app.on('before-quit',event=>{if(quitting)return;event.preventDefault();quitting=true;try{if(sessionPath&&!smoke)writeFileSync(sessionPath,JSON.stringify({clean:true,closedAt:Date.now()}));log('shutdown','Clean shutdown')}catch{}audienceWindow?.destroy();library?.close();server?.close(()=>app.quit())});
